"""Add round number

Revision ID: 054fc3f2c18c
Revises: 1bbb04350fb5
Create Date: 2021-12-28 20:22:16.127765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054fc3f2c18c'
down_revision = '1bbb04350fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_round', sa.Column('round_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_round', 'round_number')
    # ### end Alembic commands ###
