"""Initial migration.

Revision ID: 147bb1e92a0f
Revises: 
Create Date: 2021-11-21 23:19:04.354183

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '147bb1e92a0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.String(length=256), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('game',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('user_id', sa.String(length=256), nullable=True),
                    sa.Column('game_type', sa.String(
                        length=256), nullable=True),
                    sa.Column('final_score', sa.Integer(), nullable=True),
                    sa.Column('best_arm_guess', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('arm',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('game_id', sa.Integer(), nullable=True),
                    sa.Column('index', sa.Integer(), nullable=True),
                    sa.Column('mean', sa.Float(), nullable=True),
                    sa.Column('variance', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('game_round',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('game_id', sa.Integer(), nullable=True),
                    sa.Column('arm_choice', sa.Integer(), nullable=True),
                    sa.Column('recommendation', sa.Integer(), nullable=True),
                    sa.Column('observed_reward', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_round')
    op.drop_table('arm')
    op.drop_table('game')
    op.drop_table('user')
    # ### end Alembic commands ###
